configName: sam_da1_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMDA1J16B
projectName: ''
settings:
  PackageFilter: bsp;core;csp;csp_apps_pic32cm_jh00_jh01;csp_apps_pic32mx;csp_apps_pic32mz_ef;csp_apps_sam_d10;csp_apps_sam_d11;csp_apps_sam_d20;csp_apps_sam_d21_da1;csp_apps_sam_g55;csp_apps_sam_ha1;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMDA1_DFP\2.4.61\atdf\ATSAMDA1J16B.atdf
