configName: sam_d21_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../..
processor: ATSAMD21J18A
projectName: ''
settings:
  PackageFilter: bootloader;bootloader_apps_i2c;bootloader_apps_usb;bsp;core;csp;usb
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMD21_DFP\3.4.112\samd21a\atdf\ATSAMD21J18A.atdf
