configName: sam_da1_xpro
folderName: ''
format_version: v1.0
frameworkPath: ../../../../../../../..
processor: ATSAMDA1J16B
projectName: ''
settings:
  PackageFilter: bootloader;bsp;core;crypto;cryptoauthlib;csp;gfx;micrium_ucos3;net;touch;usb;
  FORCE_OPTIMIZATION: 'false'
  GENERATE_BACKUP: 'true'
  CMSISPath: .\dev_packs\arm\CMSIS\5.8.0
  MERGE_STRATEGY: USER_ALL
  DFPPath: .\dev_packs\Microchip\SAMDA1_DFP\2.3.56\atdf\ATSAMDA1J16B.atdf
